version: '3'
services:
  tcs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    image: tcs:latest
    environment:
      # 指明程序使用的配置文件
      configPath: ./conf/config.yaml
      # 指明程序监听端口
      port: 8081
    volumes:
      # 挂载配置文件
      - ./conf:/app/conf
      - ./app/data:/app/data
    ports:
      - 8080:8081
    working_dir: /app
    command: ./tcs
    restart: always

  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci', '--skip-character-set-client-handshake']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tcs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

#  nginx:
#      image: nginx:latest
#      volumes:
#        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      ports:
#        - 8088:8088
#        - 80:80
#      depends_on:
#        - tcs

