debug: true
jwt_secret: APPihWUl9uD6W4kI
log_level: info
statistics: 5
mysql:
  address: localhost
  user: root
  password: admin123
  port: 3306
  db_name: tcs
  max_idle: 10
  max_open: 100
  charset: utf8
  log_mode: true
  loc: Asia/Shanghai
swag:
  host: 8.8.8.159:8080
  base_path: /api