// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/common/user/login": {
            "post": {
                "description": "登陆接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "登陆接口",
                "parameters": [
                    {
                        "description": "账号",
                        "name": "mobile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.UserLoginArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录",
                        "schema": {
                            "$ref": "#/definitions/server.UserLoginVO"
                        }
                    }
                }
            }
        },
        "/common/user/register": {
            "post": {
                "description": "创建用户接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "创建用户接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "true_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "mobile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "身份证",
                        "name": "id_card",
                        "in": "formData"
                    }
                ]
            }
        },
        "/internal/user/detail": {
            "get": {
                "description": "获取用户信息接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户信息接口",
                "responses": {
                    "200": {
                        "description": "detail",
                        "schema": {
                            "$ref": "#/definitions/server.UserDetailVO"
                        }
                    }
                }
            }
        },
        "/internal/user/search": {
            "post": {
                "description": "查询用户列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "查询用户列表接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "根据手机号和姓名进行模糊查询",
                        "name": "search",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page_size",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "formData",
                        "required": true
                    }
                ]
            }
        }
    },
    "definitions": {
        "server.UserDetailVO": {
            "type": "object",
            "properties": {
                "mobile": {
                    "description": "手机号码",
                    "type": "string"
                },
                "true_name": {
                    "type": "string"
                }
            }
        },
        "server.UserLoginArgs": {
            "type": "object",
            "properties": {
                "mobile": {
                    "type": "string",
                    "example": "12345678"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "server.UserLoginVO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
